import asus from "../../assest/images/asus.jpg"
import asus1 from "../../assest/images/asus1.jpg"
import asus2 from "../../assest/images/asus.jpg";
import asus3 from "../../assest/images/asus3.jpg";
import asus4 from "../../assest/images/asus4.jpg";
export function getBrowsingData(param) {
  return [
    {
      id: 0,
      prodimg: asus,
      prodname: "Asus k15",
      prod_detail1: "Windows 11 Home - ASUS",
      prod_detail2: "Intel® Evo™ certified laptop",
      prod_detail3: "Windows 11 Home - ASUS",
      prod_detail4: "Intel® Evo™ certified laptop",
      prod_detail5: "Windows 11 Home - ASUS",
      prod_detail6: "Intel® Evo™ certified laptop",
      prod_detail7: "Windows 11 Home - ASUS",
      prod_detail8: "Intel® Evo™ certified laptop",
      price: "$380",
      quantity: 0,
    },
    {
      id: 1,
      prodimg: asus1,
      prodname: "Asus k15",
      prod_detail1: "Windows 11 Home - ASUS",
      prod_detail2: "Intel® Evo™ certified laptop",
      prod_detail3: "Windows 11 Home - ASUS",
      prod_detail4: "Intel® Evo™ certified laptop",
      prod_detail5: "Windows 11 Home - ASUS",
      prod_detail6: "Intel® Evo™ certified laptop",
      prod_detail7: "Windows 11 Home - ASUS",
      prod_detail8: "Intel® Evo™ certified laptop",
      price: "$380",
      quantity: 0,
    },
    {
      id: 2,
      prodimg: asus2,
      prodname: "Asus k15",
      prod_detail1: "Windows 11 Home - ASUS",
      prod_detail2: "Intel® Evo™ certified laptop",
      prod_detail3: "Windows 11 Home - ASUS",
      prod_detail4: "Intel® Evo™ certified laptop",
      prod_detail5: "Windows 11 Home - ASUS",
      prod_detail6: "Intel® Evo™ certified laptop",
      prod_detail7: "Windows 11 Home - ASUS",
      prod_detail8: "Intel® Evo™ certified laptop",
      price: "$380",
      quantity: 0,
    },
    {
      id: 3,
      prodimg: asus3,
      prodname: "Asus k15",
      prod_detail1: "Windows 11 Home - ASUS",
      prod_detail2: "Intel® Evo™ certified laptop",
      prod_detail3: "Windows 11 Home - ASUS",
      prod_detail4: "Intel® Evo™ certified laptop",
      prod_detail5: "Windows 11 Home - ASUS",
      prod_detail6: "Intel® Evo™ certified laptop",
      prod_detail7: "Windows 11 Home - ASUS",
      prod_detail8: "Intel® Evo™ certified laptop",
      price: "$380",
      quantity: 0,
    },
    {
      id: 4,
      prodimg: asus4,
      prodname: "Asus k15",
      prod_detail1: "Windows 11 Home - ASUS",
      prod_detail2: "Intel® Evo™ certified laptop",
      prod_detail3: "Windows 11 Home - ASUS",
      prod_detail4: "Intel® Evo™ certified laptop",
      prod_detail5: "Windows 11 Home - ASUS",
      prod_detail6: "Intel® Evo™ certified laptop",
      prod_detail7: "Windows 11 Home - ASUS",
      prod_detail8: "Intel® Evo™ certified laptop",
      price: "$380",
      quantity: 0,
    },
    {
      id: 5,
      prodimg: asus,
      prodname: "Asus k15",
      prod_detail1: "Windows 11 Home - ASUS",
      prod_detail2: "Intel® Evo™ certified laptop",
      prod_detail3: "Windows 11 Home - ASUS",
      prod_detail4: "Intel® Evo™ certified laptop",
      prod_detail5: "Windows 11 Home - ASUS",
      prod_detail6: "Intel® Evo™ certified laptop",
      prod_detail7: "Windows 11 Home - ASUS",
      prod_detail8: "Intel® Evo™ certified laptop",
      price: "$380",
      quantity: 0,
    },
  ];
}